/*****************************************************************************/
/*                                                                           */
/* Programmer: Tyrone Turrell                                                */
/* C Programs Jim Cannings Programming Problems                              */
/*                                                                           */
/*                                             */
/* Created: SEP 25 2020                                                      */
/*                                                                           */
/* Program 50: Non-polymorphic Linked List                                   */
/*                                                                           */
/* Write a C program that reads in integers from the keyboard. Your program  */
/* should then build a linked list in the heap. Each node of the list        */
/* contains an integer and a pointer to the next node in the list. The final */
/* node in the list has a null pointer. Your program should insert integers  */
/* into the front of the list.  After end-of-file has been generated by the  */
/* user, your program uses the list to print out the integers in the order   */
/* in which they were typed in. That is, you need to print the tail of the   */
/* list first. This can be easily done using a recursive strategy for        */
/* printing. Hey, how does the user generate EOF from the keyboard?  Your    */
/* textbook explains this in chapter 1. Your textbook is your best friend.   */
/*                                                                           */
/* Approximate Completition Time:  1 mins                                    */
/*                                                                           */
/* UPDATED:                                                                  */
/*                                                                           */
/*****************************************************************************/



#include <stdio.h> 	                //for input/output

// Begin Main
int main( int argc, char *argv[ ] )
{
  
  printf("\n\nHello World\n\n");

  
  return 0;


} // End Main
