/*****************************************************************************/
/*                                                                           */
/* Programmer: Tyrone Turrell                                                */
/* C Programs Jim Cannings Programming Problems                              */
/*                                                                           */
/*                                             */
/* Created: SEP 25 2020                                                      */
/*                                                                           */
/* Program 55 : Fibonacci Sequence(Recursive)                                */
/*                                                                           */
/* The Fibonacci sequence is 1,                                              */
/*            1,                                                             */
/*             2,                                                            */
/*             3,                                                            */
/*            5,                                                             */
/*            8,                                                             */
/*            13,                                                            */
/*            21,                                                            */
/*            34,                                                            */
/*            55,                                                            */
/*            �                                                             */
/*                                                                           */
/* The first term is 1. The second term is 1. Each term thereafter is the    */
/* sum of the previous two terms.                                            */
/*                                                                           */
/* Write a C program that contains a function called Fibonacci.This          */
/* function, when given a integer n >= 1, will return the nth Fibonacci      */
/* number.The function should use a recursive strategy.The main function     */
/* should prompt the user to enter numbers until EOF is generated by the     */
/* user.Do not use an array in the program.                                  */
/*                               */
/* Approximate Completition Time:  1 mins                                    */
/*                                                                           */
/* UPDATED:                                                                  */
/*                                                                           */
/*                                                                           */
/*****************************************************************************/

#include <stdio.h> 	                //for input/output

             // Begin Main
             int main(int argc, char *argv[])
{
  
  printf("\n\nHello World\n\n");

  
  return 0;


} // End Main
